(function(f,g,e,c,h,n,l){f.GoogleAnalyticsObject=h;f[h]=f[h]||function(){(f[h].q=f[h].q||[]).push(arguments)};f[h].l=1*new Date;n=g.createElement(e);l=g.getElementsByTagName(e)[0];n.async=1;n.src=c;l.parentNode.insertBefore(n,l)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-43015655-1","jonmann20.github.io");ga("send","pageview");
(function(f,g){(function(e){"function"===typeof define&&define.amd?define(["jquery"],e):f.sammy=g.Sammy=e(f)})(function(e){var c,h=/:([\w\d]+)/g,f=/\?([^#]*)?$/,l=function(a){return Array.prototype.slice.call(a)},k=function(a){return"[object Function]"===Object.prototype.toString.call(a)},m=function(a){return"[object Array]"===Object.prototype.toString.call(a)},u=function(a){return decodeURIComponent((a||"").replace(/\+/g," "))},w=encodeURIComponent,x=function(a){return String(a).replace(/&(?!\w+;)/g,
"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")},p=function(a){return function(){return this.route.apply(this,[a].concat(Array.prototype.slice.call(arguments)))}},s={},r=!(!g.history||!history.pushState),y=[];c=function(){var a=l(arguments),b,d;c.apps=c.apps||{};if(0===a.length||a[0]&&k(a[0]))return c.apply(c,["body"].concat(a));if("string"==typeof(d=a.shift()))return b=c.apps[d]||new c.Application,b.element_selector=d,0<a.length&&e.each(a,function(a,d){b.use(d)}),b.element_selector!=
d&&delete c.apps[d],c.apps[b.element_selector]=b};c.VERSION="0.7.4";c.addLogger=function(a){y.push(a)};c.log=function(){var a=l(arguments);a.unshift("["+Date()+"]");e.each(y,function(b,d){d.apply(c,a)})};"undefined"!=typeof g.console?k(g.console.log.apply)?c.addLogger(function(){g.console.log.apply(g.console,arguments)}):c.addLogger(function(){g.console.log(arguments)}):"undefined"!=typeof console&&c.addLogger(function(){console.log.apply(console,arguments)});e.extend(c,{makeArray:l,isFunction:k,
isArray:m});c.Object=function(a){return e.extend(this,a||{})};e.extend(c.Object.prototype,{escapeHTML:x,h:x,toHash:function(){var a={};e.each(this,function(b,d){k(d)||(a[b]=d)});return a},toHTML:function(){var a="";e.each(this,function(b,d){k(d)||(a+="<strong>"+b+"</strong> "+d+"<br />")});return a},keys:function(a){var b=[],d;for(d in this)k(this[d])&&a||b.push(d);return b},has:function(a){return this[a]&&""!==e.trim(this[a].toString())},join:function(){var a=l(arguments),b=a.shift();return a.join(b)},
log:function(){c.log.apply(c,arguments)},toString:function(a){var b=[];e.each(this,function(d,q){k(q)&&!a||b.push('"'+d+'": '+q.toString())});return"Sammy.Object: {"+b.join(",")+"}"}});c.targetIsThisWindow=function(a){return(a=e(a.target).attr("target"))&&a!==g.name&&"_self"!==a?"_blank"===a?!1:"top"===a&&g===g.top?!0:!1:!0};c.DefaultLocationProxy=function(a,b){this.app=a;this.is_native=!1;this.has_history=r;this._startPolling(b)};c.DefaultLocationProxy.fullPath=function(a){var b=a.toString().match(/^[^#]*(#.+)$/);
return[a.pathname,a.search,b?b[1]:""].join("")};e.extend(c.DefaultLocationProxy.prototype,{bind:function(){var a=this,b=this.app,d=c.DefaultLocationProxy;e(g).bind("hashchange."+this.app.eventNamespace(),function(q,e){!1!==a.is_native||e||(a.is_native=!0,g.clearInterval(d._interval),d._interval=null);b.trigger("location-changed")});r&&!b.disable_push_state&&(e(g).bind("popstate."+this.app.eventNamespace(),function(a){b.trigger("location-changed")}),e(document).delegate("a","click.history-"+this.app.eventNamespace(),
function(q){if(!(q.isDefaultPrevented()||q.metaKey||q.ctrlKey)){var e=d.fullPath(this);if(this.hostname==g.location.hostname&&b.lookupRoute("get",e)&&c.targetIsThisWindow(q))return q.preventDefault(),a.setLocation(e),!1}}));d._bindings||(d._bindings=0);d._bindings++},unbind:function(){e(g).unbind("hashchange."+this.app.eventNamespace());e(g).unbind("popstate."+this.app.eventNamespace());e(document).undelegate("a","click.history-"+this.app.eventNamespace());c.DefaultLocationProxy._bindings--;0>=c.DefaultLocationProxy._bindings&&
(g.clearInterval(c.DefaultLocationProxy._interval),c.DefaultLocationProxy._interval=null)},getLocation:function(){return c.DefaultLocationProxy.fullPath(g.location)},setLocation:function(a){/^([^#\/]|$)/.test(a)&&(a=r&&!this.app.disable_push_state?"/"+a:"#!/"+a);if(a!=this.getLocation())if(r&&!this.app.disable_push_state&&/^\//.test(a))history.pushState({path:a},g.title,a),this.app.trigger("location-changed");else return g.location=a},_startPolling:function(a){var b=this;if(!c.DefaultLocationProxy._interval){a||
(a=10);var d=function(){var a=b.getLocation();"undefined"!=typeof c.DefaultLocationProxy._last_location&&a==c.DefaultLocationProxy._last_location||g.setTimeout(function(){e(g).trigger("hashchange",[!0])},0);c.DefaultLocationProxy._last_location=a};d();c.DefaultLocationProxy._interval=g.setInterval(d,a)}}});c.Application=function(a){var b=this;this.routes={};this.listeners=new c.Object({});this.arounds=[];this.befores=[];this.namespace=(new Date).getTime()+"-"+parseInt(1E3*Math.random(),10);this.context_prototype=
function(){c.EventContext.apply(this,arguments)};this.context_prototype.prototype=new c.EventContext;k(a)&&a.apply(this,[this]);this._location_proxy||this.setLocationProxy(new c.DefaultLocationProxy(this,this.run_interval_every));this.debug&&this.bindToAllEvents(function(a,e){b.log(b.toString(),a.cleaned_type,e||{})})};c.Application.prototype=e.extend({},c.Object.prototype,{ROUTE_VERBS:["get","post","put","delete"],APP_EVENTS:"run unload lookup-route run-route route-found event-context-before event-context-after changed error check-form-submission redirect location-changed".split(" "),
_last_route:null,_location_proxy:null,_running:!1,element_selector:"body",debug:!1,raise_errors:!1,run_interval_every:50,disable_push_state:!1,template_engine:null,toString:function(){return"Sammy.Application:"+this.element_selector},$element:function(a){return a?e(this.element_selector).find(a):e(this.element_selector)},use:function(){var a=l(arguments),b=a.shift(),d=b||"";try{a.unshift(this),"string"==typeof b&&(d="Sammy."+b,b=c[b]),b.apply(this,a)}catch(e){"undefined"===typeof b?this.error("Plugin Error: called use() but plugin ("+
d.toString()+") is not defined",e):k(b)?this.error("Plugin Error",e):this.error("Plugin Error: called use() but '"+d.toString()+"' is not a function",e)}return this},setLocationProxy:function(a){var b=this._location_proxy;this._location_proxy=a;this.isRunning()&&(b&&b.unbind(),this._location_proxy.bind())},log:function(){c.log.apply(c,Array.prototype.concat.apply([this.element_selector],arguments))},route:function(a,b){var d=this,c=[],v,f,t=Array.prototype.slice.call(arguments,2);0===t.length&&k(b)&&
(b=a,t=[b],a="any");a=a.toLowerCase();if(b.constructor==String){for(h.lastIndex=0;null!==(f=h.exec(b));)c.push(f[1]);b=RegExp(b.replace(h,"([^/]+)")+"$")}e.each(t,function(a,b){"string"===typeof b&&(t[a]=d[b])});v=function(a){var e={verb:a,path:b,callback:t,param_names:c};d.routes[a]=d.routes[a]||[];d.routes[a].push(e)};"any"===a?e.each(this.ROUTE_VERBS,function(a,b){v(b)}):v(a);return this},get:p("get"),post:p("post"),put:p("put"),del:p("delete"),any:p("any"),mapRoutes:function(a){var b=this;e.each(a,
function(a,e){b.route.apply(b,e)});return this},eventNamespace:function(){return["sammy-app",this.namespace].join("-")},bind:function(a,b,d){var e=this;"undefined"==typeof d&&(d=b);b=function(a,b){var c;b&&b.context?(c=b.context,delete b.context):c=new e.context_prototype(e,"bind",a.type,b,a.target);a.cleaned_type=a.type.replace(e.eventNamespace(),"");d.apply(c,[a,b])};this.listeners[a]||(this.listeners[a]=[]);this.listeners[a].push(b);this.isRunning()&&this._listen(a,b);return this},trigger:function(a,
b){this.$element().trigger([a,this.eventNamespace()].join("."),[b]);return this},refresh:function(){this.last_location=null;this.trigger("location-changed");return this},before:function(a,b){k(a)&&(b=a,a={});this.befores.push([a,b]);return this},after:function(a){return this.bind("event-context-after",a)},around:function(a){this.arounds.push(a);return this},onComplete:function(a){this._onComplete=a;return this},isRunning:function(){return this._running},helpers:function(a){e.extend(this.context_prototype.prototype,
a);return this},helper:function(a,b){this.context_prototype.prototype[a]=b;return this},run:function(a){if(this.isRunning())return!1;var b=this;e.each(this.listeners.toHash(),function(a,c){e.each(c,function(e,c){b._listen(a,c)})});this.trigger("run",{start_url:a});this._running=!0;this.last_location=null;/\#(.+)/.test(this.getLocation())||"undefined"==typeof a||this.setLocation(a);this._checkLocation();this._location_proxy.bind();this.bind("location-changed",function(){b._checkLocation()});this.bind("submit",
function(a){return c.targetIsThisWindow(a)?!1===b._checkFormSubmission(e(a.target).closest("form"))?a.preventDefault():!1:!0});e(g).bind("unload",function(){b.unload()});return this.trigger("changed")},unload:function(){if(!this.isRunning())return!1;var a=this;this.trigger("unload");this._location_proxy.unbind();this.$element().unbind("submit").removeClass(a.eventNamespace());e.each(this.listeners.toHash(),function(b,d){e.each(d,function(d,e){a._unlisten(b,e)})});this._running=!1;return this},destroy:function(){this.unload();
delete c.apps[this.element_selector];return this},bindToAllEvents:function(a){var b=this;e.each(this.APP_EVENTS,function(d,e){b.bind(e,a)});e.each(this.listeners.keys(!0),function(d,c){-1==e.inArray(c,b.APP_EVENTS)&&b.bind(c,a)});return this},routablePath:function(a){return a.replace(f,"")},lookupRoute:function(a,b){var d=!1,e=0,c,h;if("undefined"!=typeof this.routes[a])for(c=this.routes[a].length;e<c;e++)if(h=this.routes[a][e],this.routablePath(b).match(h.path)){d=h;break}return d},runRoute:function(a,
b,d,c){var h=this,f=this.lookupRoute(a,b),g,l,n,k,m,p,r;this.debug&&this.log("runRoute",[a,b].join(" "));this.trigger("run-route",{verb:a,path:b,params:d});"undefined"==typeof d&&(d={});e.extend(d,this._parseQueryString(b));if(f){this.trigger("route-found",{route:f});null!==(p=f.path.exec(this.routablePath(b)))&&(p.shift(),e.each(p,function(a,b){f.param_names[a]?d[f.param_names[a]]=u(b):(d.splat||(d.splat=[]),d.splat.push(u(b)))}));g=new this.context_prototype(this,a,b,d,c);c=this.arounds.slice(0);
n=this.befores.slice(0);m=[g];d.splat&&(m=m.concat(d.splat));l=function(){for(var a,b,d;0<n.length;)if(k=n.shift(),h.contextMatchesOptions(g,k[0])&&(a=k[1].apply(g,[g]),!1===a))return!1;h.last_route=f;g.trigger("event-context-before",{context:g});"function"===typeof f.callback&&(f.callback=[f.callback]);f.callback&&f.callback.length&&(b=-1,d=function(){b++;f.callback[b]?a=f.callback[b].apply(g,m):h._onComplete&&typeof("function"===h._onComplete)&&h._onComplete(g)},m.push(d),d());g.trigger("event-context-after",
{context:g});return a};e.each(c.reverse(),function(a,b){var d=l;l=function(){return b.apply(g,[d])}});try{r=l()}catch(s){this.error(["500 Error",a,b].join(" "),s)}return r}return this.notFound(a,b)},contextMatchesOptions:function(a,b,d){if("string"===typeof b||"[object RegExp]"===Object.prototype.toString.call(b))b={path:b};"undefined"===typeof d&&(d=!0);if(e.isEmptyObject(b))return!0;if(m(b.path)){var c,f,h,g;c=[];f=0;for(g=b.path.length;f<g;f+=1)h=e.extend({},b,{path:b.path[f]}),c.push(this.contextMatchesOptions(a,
h));a=-1<e.inArray(!0,c)?!0:!1;return d?a:!a}if(b.only)return this.contextMatchesOptions(a,b.only,!0);if(b.except)return this.contextMatchesOptions(a,b.except,!1);f=c=!0;b.path&&("[object RegExp]"!==Object.prototype.toString.call(b.path)&&(b.path=RegExp(b.path.toString()+"$")),c=b.path.test(a.path));b.verb&&(f="string"===typeof b.verb?b.verb===a.verb:-1<b.verb.indexOf(a.verb));return d?f&&c:!(f&&c)},getLocation:function(){return this._location_proxy.getLocation()},setLocation:function(a){return this._location_proxy.setLocation(a)},
swap:function(a,b){var d=this.$element().html(a);k(b)&&b(a);return d},templateCache:function(a,b){return"undefined"!=typeof b?s[a]=b:s[a]},clearTemplateCache:function(){return s={}},notFound:function(a,b){var d=this.error(["404 Not Found",a,b].join(" "));return"get"===a?d:!0},error:function(a,b){b||(b=Error());b.message=[a,b.message].join(" ");this.trigger("error",{message:b.message,error:b});if(this.raise_errors)throw b;this.log(b.message,b)},_checkLocation:function(){var a,b;a=this.getLocation();
this.last_location&&"get"==this.last_location[0]&&this.last_location[1]==a||(this.last_location=["get",a],b=this.runRoute("get",a));return b},_getFormVerb:function(a){a=e(a);var b,d;d=a.find('input[name="_method"]');0<d.length&&(b=d.val());b||(b=a[0].getAttribute("method"));b&&""!==b||(b="get");return e.trim(b.toString().toLowerCase())},_checkFormSubmission:function(a){var b,d,c;this.trigger("check-form-submission",{form:a});b=e(a);d=b.attr("action")||"";c=this._getFormVerb(b);this.debug&&this.log("_checkFormSubmission",
b,d,c);"get"===c?(b=this._serializeFormParams(b),""!==b&&(d+="?"+b),this.setLocation(d),a=!1):(b=e.extend({},this._parseFormParams(b)),a=this.runRoute(c,d,b,a.get(0)));return"undefined"==typeof a?!1:a},_serializeFormParams:function(a){var b="";a=a.serializeArray();var d;if(0<a.length)for(b=this._encodeFormPair(a[0].name,a[0].value),d=1;d<a.length;d++)b=b+"&"+this._encodeFormPair(a[d].name,a[d].value);return b},_encodeFormPair:function(a,b){return w(a)+"="+w(b)},_parseFormParams:function(a){var b=
{};a=a.serializeArray();var d;for(d=0;d<a.length;d++)b=this._parseParamPair(b,a[d].name,a[d].value);return b},_parseQueryString:function(a){var b={},d,c;if((a=a.match(f))&&a[1])for(a=a[1].split("&"),c=0;c<a.length;c++)d=a[c].split("="),b=this._parseParamPair(b,u(d[0]),u(d[1]||""));return b},_parseParamPair:function(a,b,d){"undefined"!==typeof a[b]?m(a[b])?a[b].push(d):a[b]=[a[b],d]:a[b]=d;return a},_listen:function(a,b){return this.$element().bind([a,this.eventNamespace()].join("."),b)},_unlisten:function(a,
b){return this.$element().unbind([a,this.eventNamespace()].join("."),b)}});c.RenderContext=function(a){this.event_context=a;this.callbacks=[];this.content=this.previous_content=null;this.waiting=this.next_engine=!1};c.RenderContext.prototype=e.extend({},c.Object.prototype,{then:function(a){if(!k(a))if("string"===typeof a&&a in this.event_context){var b=this.event_context[a];a=function(a){return b.apply(this.event_context,[a])}}else return this;var d=this;this.waiting?this.callbacks.push(a):(this.wait(),
g.setTimeout(function(){var b=a.apply(d,[d.content,d.previous_content]);!1!==b&&d.next(b)},0));return this},wait:function(){this.waiting=!0},next:function(a){this.waiting=!1;"undefined"!==typeof a&&(this.previous_content=this.content,this.content=a);0<this.callbacks.length&&this.then(this.callbacks.shift())},load:function(a,b,d){var c=this;return this.then(function(){var f,h,g;k(b)?(d=b,b={}):b=e.extend({},b);d&&this.then(d);if("string"===typeof a){f=(g=a.match(/\.json$/)||b.json)?!0===b.cache:!1!==
b.cache;c.next_engine=c.event_context.engineFor(a);delete b.cache;delete b.json;b.engine&&(c.next_engine=b.engine,delete b.engine);if(f&&(h=this.event_context.app.templateCache(a)))return h;this.wait();e.ajax(e.extend({url:a,data:{},dataType:g?"json":"text",type:"get",success:function(b){f&&c.event_context.app.templateCache(a,b);c.next(b)}},b));return!1}if(a.nodeType)return a.innerHTML;if(a.selector)return c.next_engine=a.attr("data-engine"),!1===b.clone?a.remove()[0].innerHTML.toString():a[0].innerHTML.toString()})},
loadPartials:function(a){var b;if(a)for(b in this.partials=this.partials||{},a)(function(b,c){b.load(a[c]).then(function(a){this.partials[c]=a})})(this,b);return this},render:function(a,b,d,c){if(k(a)&&!b)return this.then(a);k(b)?(c=d,d=b,b=null):d&&!k(d)&&(c=d,d=null);return this.loadPartials(c).load(a).interpolate(b,a).then(d)},partial:function(a,b,d,c){return k(d)?this.render(a,b,c).swap(d):k(b)?this.render(a,{},d).swap(b):this.render(a,b,d).swap()},send:function(){var a=this,b=l(arguments),d=
b.shift();m(b[0])&&(b=b[0]);return this.then(function(c){b.push(function(b){a.next(b)});a.wait();d.apply(d,b);return!1})},collect:function(a,b,d){var c=this,f=function(){k(a)&&(b=a,a=this.content);var d=[],f=!1;e.each(a,function(a,e){var h=b.apply(c,[a,e]);h.jquery&&1==h.length&&(h=h[0],f=!0);d.push(h);return h});return f?d:d.join("")};return d?f():this.then(f)},renderEach:function(a,b,d,c){m(b)&&(c=d,d=b,b=null);return this.load(a).then(function(f){var h=this;d||(d=m(this.previous_content)?this.previous_content:
[]);if(c)e.each(d,function(d,e){var g={},l=this.next_engine||a;b?g[b]=e:g=e;c(e,h.event_context.interpolate(f,g,l))});else return this.collect(d,function(d,c){var e={},h=this.next_engine||a;b?e[b]=c:e=c;return this.event_context.interpolate(f,e,h)},!0)})},interpolate:function(a,b,d){var c=this;return this.then(function(e,f){!a&&f&&(a=f);this.next_engine&&(b=this.next_engine,this.next_engine=!1);var h=c.event_context.interpolate(e,a,b,this.partials);return d?f+h:h})},swap:function(a){return this.then(function(b){this.event_context.swap(b,
a);return b}).trigger("changed",{})},appendTo:function(a){return this.then(function(b){e(a).append(b)}).trigger("changed",{})},prependTo:function(a){return this.then(function(b){e(a).prepend(b)}).trigger("changed",{})},replace:function(a){return this.then(function(b){e(a).html(b)}).trigger("changed",{})},trigger:function(a,b){return this.then(function(d){"undefined"==typeof b&&(b={content:d});this.event_context.trigger(a,b);return d})}});c.EventContext=function(a,b,d,e,f){this.app=a;this.verb=b;this.path=
d;this.params=new c.Object(e);this.target=f};c.EventContext.prototype=e.extend({},c.Object.prototype,{$element:function(){return this.app.$element(l(arguments).shift())},engineFor:function(a){var b;if(k(a))return a;a=(a||this.app.template_engine).toString();if(b=a.match(/\.([^\.\?\#]+)$/))a=b[1];return a&&k(this[a])?this[a]:this.app.template_engine?this.engineFor(this.app.template_engine):function(a,b){return a}},interpolate:function(a,b,d,c){return this.engineFor(d).apply(this,[a,b,c])},render:function(a,
b,d,e){return(new c.RenderContext(this)).render(a,b,d,e)},renderEach:function(a,b,d,e){return(new c.RenderContext(this)).renderEach(a,b,d,e)},load:function(a,b,d){return(new c.RenderContext(this)).load(a,b,d)},loadPartials:function(a){return(new c.RenderContext(this)).loadPartials(a)},partial:function(a,b,d,e){return(new c.RenderContext(this)).partial(a,b,d,e)},send:function(){var a=new c.RenderContext(this);return a.send.apply(a,arguments)},redirect:function(){var a;a=l(arguments);var b=this.app.getLocation(),
c=a.length;if(1<c){for(var f=0,h=[],g=[],n={},k=!1;f<c;f++)"string"==typeof a[f]?h.push(a[f]):(e.extend(n,a[f]),k=!0);a=h.join("/");if(k){for(var m in n)g.push(this.app._encodeFormPair(m,n[m]));a+="?"+g.join("&")}}else a=a[0];this.trigger("redirect",{to:a});this.app.last_location=[this.verb,this.path];this.app.setLocation(a);RegExp(a).test(b)&&this.app.trigger("location-changed")},trigger:function(a,b){"undefined"==typeof b&&(b={});b.context||(b.context=this);return this.app.trigger(a,b)},eventNamespace:function(){return this.app.eventNamespace()},
swap:function(a,b){return this.app.swap(a,b)},notFound:function(){return this.app.notFound(this.verb,this.path)},json:function(a){return e.parseJSON(a)},toString:function(){return"Sammy.EventContext: "+[this.verb,this.path,this.params].join(" ")}});return c})})(jQuery,window);
jw.Utils=function(f,g){var e={"//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js":!1,"//platform.twitter.com/widgets.js":!1,"/js/plugins/jquery.cycle.lite.js":!1,"/js/plugins/jquery.hoverIntent.min.js":!1,"/js/plugins/jquery.hoverCarousel.js":!1,"/js/plugins/jquery.star_bg.js":!1,"/js/stars.js":!1,"/js/ballPit.js":!1,"/js/bouncingObj.js":!1,"/js/computerGraphics/web/computergraphics.dart.js":!1,"/js/ustream.js":!1};return{require:function(c,h){e[c]?h(!0):f.ajax({url:c,dataType:"script",
success:function(f){e[c]=!0;h(!1)}})},getYear:function(){return(new Date).getFullYear()},resetModel:function(){"ballPit"===jw.Routing.lastPg?jw.BallPit.deInit():"stars"===jw.Routing.lastPg?jw.StarryBg.deInit():"bObj"===jw.Routing.lastPg&&jw.Bounce.deInit();jw.main.empty();jw.body.removeClass();document.title="";f("meta[name=description], meta[name=keywords]").remove();f("meta[name=robots]").remove();f(".dPlaygroundNav").hide()}}}(jQuery);
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||function(f){window.setTimeout(f,1E3/60)}}();
jw.HomeModel=function(f,g){return{render:function(e){jw.Utils.resetModel();e.load("/home.html",function(c){jw.main.html(c);jw.Utils.require("//platform.twitter.com/widgets.js",function(c){twttr.widgets.load()});jw.Utils.require("/js/plugins/jquery.cycle.lite.js",function(c){f("#slideshow").cycle()})});document.title="Jon Wiedmann";jw.head.append("<meta name='description' content='Jon Wiedmann&#700;s personal website.  This site is set up to showcase some of my technical ability. This site has information regarding my work experience and hobbies.' /><meta name='keywords' content='Jon Wiedmann, Web Developer, PHP, HTML5, CSS, jQuery, Javascript, sammy.js' />");
jw.body.addClass("home")}}}(jQuery);jw.AboutModel=function(f,g){return{render:function(e){jw.Utils.resetModel();e.load("/about.html",function(c){jw.main.html(c)});document.title="About";jw.body.addClass("about")}}}(jQuery);jw.ContactModel=function(f,g){return{render:function(e){jw.Utils.resetModel();e.load("/contact.html",function(c){jw.main.html(c)});document.title="Contact Me";jw.body.addClass("contact")}}}(jQuery);
jw.FavoritesModel=function(f,g){return{render:function(e){jw.Utils.resetModel();e.load("/favorites.html",function(c){jw.main.html(c)});document.title="Favorites";jw.head.append("<meta name='description' content='Jon Wiedmann&#700;s personal website.  This site is set up to showcase some of my technical ability. This site has information regarding my work experience and hobbies.' /><meta name='keywords' content='Jon Wiedmann, Web Developer, PHP, HTML5, CSS, jQuery, Javascript, sammy.js' />");jw.body.addClass("favs nav0")}}}(jQuery);
jw.BlogModel=function(f,g){return{render:function(e){jw.Utils.resetModel();e.load("/blog/index.html",function(c){jw.main.html(c)});document.title="Blog";jw.body.addClass("blog")}}}(jQuery);
jw.GamesModel=function(f,g){return{render:function(e,c){jw.Utils.resetModel();"index"===c&&(e.load("/games/index.html",function(c){jw.main.html(c);jw.Utils.require("/js/plugins/jquery.hoverIntent.min.js",function(){});jw.Utils.require("/js/plugins/jquery.hoverCarousel.js",function(){f("ul").hoverCarousel()})}),document.title="Games",jw.body.addClass("absHover games"))}}}(jQuery);
jw.MusicModel=function(f,g){function e(c){c.load("/music/musicNav.html",function(c){f(".musicNav").html(c)})}var c=jw.Utils.getYear();return{render:function(h,g){jw.Utils.resetModel();"index"===g?(h.load("/music/index.html",function(g){jw.main.html(g);e(h);f(".teaching").text(c-2008);f(".playing").text(c-1994)}),document.title="Music",jw.body.addClass("music musicHome")):"bass"===g?(h.load("/music/bass.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-2009)}),document.title="Bass | Music",
jw.body.addClass("music bass")):"chiptunes"===g?(h.load("/music/chiptunes.html",function(c){jw.main.html(c);e(h)}),document.title="Chiptunes | Music",jw.body.addClass("music")):"guitar"===g?(h.load("/music/guitar.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-2002)}),document.title="Guitar | Music",jw.body.addClass("music")):"mandolin"===g?(h.load("/music/mandolin.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-2008)}),document.title="Mandolin | Music",jw.body.addClass("music mandolin")):
"piano"===g?(h.load("/music/piano.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-1994)}),document.title="Piano | Music",jw.body.addClass("music")):"trumpet"===g?(h.load("/music/trumpet.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-1998)}),document.title="Trumpet | Music",jw.body.addClass("music trumpet")):"rates"===g?(h.load("/music/rates.html",function(c){jw.main.html(c);e(h)}),document.title="Rates | Music",jw.head.append("<meta name='description' content='Music Lesson Rates'><meta name='robots' rel='none' />"),
jw.body.addClass("music rates")):"voice"===g&&(h.load("/music/voice.html",function(g){jw.main.html(g);e(h);f(".playing").text(c-2009)}),document.title="Voice | Music",jw.body.addClass("music"))}}}(jQuery);
jw.PlaygroundModel=function(f,g){return{render:function(e,c){jw.Utils.resetModel();"index"===c?(e.load("/playground/index.html",function(c){jw.main.html(c);e.load("/playground/playgroundNav.html",function(c){f(".playgroundNav").html(c);f(".colL ul").hoverCarousel()})}),document.title="Playground",jw.head.append("<meta name='description' content='A canvas example showcasing a ball pit.' /><meta name='keywords' content='canvas, html5' />"),jw.body.addClass("absHover playground")):"ballPit"===c?(e.load("/playground/ballPit.html",
function(c){jw.main.html(c);jw.Utils.require("/js/ballPit.js",function(){jw.BallPit.init()})}),document.title="Ball Pit | Playground",jw.head.append("<meta name='description' content='A canvas example showcasing a ball pit.' /><meta name='keywords' content='canvas, html5' />"),jw.body.addClass("playground playInner nav3")):"stars"===c?(e.load("/playground/stars.html",function(c){jw.main.html(c);jw.Utils.require("/js/plugins/jquery.star_bg.js",function(){jw.Utils.require("/js/stars.js",function(c){jw.StarryBg.init()})})}),
document.title="Starry Background | Playground",jw.head.append("<meta name='description' content='A canvas example showcasing a starry background.' /><meta name='keywords' content='canvas, html5' />"),jw.body.addClass("playground playInner nav2")):"bObj"===c?(e.load("/playground/bouncing-object.html",function(c){jw.main.html(c);jw.Utils.require("/js/bouncingObj.js",function(){jw.Bounce.init()})}),document.title="Bouncing Object | Playground",jw.head.append("<meta name='description' content='A canvas example showcasing a bouncing object.' /><meta name='keywords' content='canvas, html5' />"),
jw.body.addClass("playground playInner nav6")):"ustream"===c?(e.load("/playground/USTREAM-demo.html",function(c){jw.main.html(c);jw.Utils.require("/js/ustream.js",function(){jw.Ustream.init()})}),document.title="USTREAM demo | Playground",jw.head.append("<meta name='description' content='A USTREAM api demo.' /><meta name='keywords' content='USTREAM' />"),jw.body.addClass("playground playInner uStreamPage nav5")):"bCube"===c?(e.load("/playground/breakdancing-cube.html",function(c){jw.main.html(c);
f("#cube").on("click",function(c){c.preventDefault()})}),document.title="Breakdancing Cube | Playground",jw.head.append("<meta name='description' content='Pure CSS3 animation demo.' /><meta name='keywords' content='CSS3, HTML5' />"),jw.body.addClass("playground playInner bDancingCube nav1")):"fSun"===c&&(e.load("/playground/floating-sun.html",function(c){jw.main.html(c);f.getScript("/js/computerGraphics/web/computergraphics.dart.js")}),document.title="Floating Sun | Playground",jw.head.append("<meta name='description' content='A canvas example showcasing a computer graphics simulation.' /><meta name='keywords' content='canvas, html5, computer graphics' />"),
jw.body.addClass("playground playInner nav4"));"index"!==c&&(f(".dPlaygroundNav").show(),e.load("/playground/playgroundNav.html",function(c){f(".dPlaygroundNav").html(c)}))}}}(jQuery);
jw.PortfolioModel=function(f,g){return{render:function(e,c){jw.Utils.resetModel();"index"===c&&(e.load("/portfolio/index.html",function(c){jw.main.html(c);jw.Utils.require("/js/plugins/jquery.hoverIntent.min.js",function(){});jw.Utils.require("/js/plugins/jquery.hoverCarousel.js",function(){f("ul").hoverCarousel()})}),document.title="Portfolio",jw.body.addClass("portfolio absHover"))}}}(jQuery);
jw.Routing=function(f,g){var e=f.sammy(function(){this.route("get","/",function(){jw.HomeModel.render(this);jw.Routing.lastPg="home"});this.route("get","#home",function(){jw.HomeModel.render(this);jw.Routing.lastPg="home"});this.route("get","#about",function(){jw.AboutModel.render(this);jw.Routing.lastPg="about"});this.route("get","#contact",function(){jw.ContactModel.render(this);jw.Routing.lastPg="contact"});this.route("get","#favorites",function(){jw.FavoritesModel.render(this);jw.Routing.lastPg=
"favorites"});this.route("get","#blog",function(){jw.BlogModel.render(this);jw.Routing.lastPg="blog"});this.route("get","#games",function(){jw.GamesModel.render(this,"index");jw.Routing.lastPg="games/index"});this.route("get","#music",function(){jw.MusicModel.render(this,"index");jw.Routing.lastPg="music/index"});this.route("get","#music/bass",function(){jw.MusicModel.render(this,"bass");jw.Routing.lastPg="music/bass"});this.route("get","#music/chiptunes",function(){jw.MusicModel.render(this,"chiptunes");
jw.Routing.lastPg="music/chiptunes"});this.route("get","#music/guitar",function(){jw.MusicModel.render(this,"guitar");jw.Routing.lastPg="music/guitar"});this.route("get","#music/mandolin",function(){jw.MusicModel.render(this,"mandolin");jw.Routing.lastPg="music/mandolin"});this.route("get","#music/piano",function(){jw.MusicModel.render(this,"piano");jw.Routing.lastPg="music/piano"});this.route("get","#music/trumpet",function(){jw.MusicModel.render(this,"trumpet");jw.Routing.lastPg="music/trumpet"});
this.route("get","#music/rates",function(){jw.MusicModel.render(this,"rates");jw.Routing.lastPg="music/rates"});this.route("get","#music/voice",function(){jw.MusicModel.render(this,"voice");jw.Routing.lastPg="music/voice"});this.route("get","#playground",function(){jw.PlaygroundModel.render(this,"index");jw.Routing.lastPg="playground/index"});this.route("get","#playground/ballPit",function(){jw.PlaygroundModel.render(this,"ballPit");jw.Routing.lastPg="ballPit"});this.route("get","#playground/breakdancing-cube",
function(){jw.PlaygroundModel.render(this,"bCube");jw.Routing.lastPg="bCube"});this.route("get","#playground/floating-sun",function(){jw.PlaygroundModel.render(this,"fSun");jw.Routing.lastPg="fSun"});this.route("get","#playground/bouncing-object",function(){jw.PlaygroundModel.render(this,"bObj");jw.Routing.lastPg="bObj"});this.route("get","#playground/starry-background",function(){jw.PlaygroundModel.render(this,"stars");jw.Routing.lastPg="stars"});this.route("get","#playground/USTREAM-demo",function(){jw.PlaygroundModel.render(this,
"ustream");jw.Routing.lastPg="ustream"});this.route("get","#portfolio",function(){jw.PortfolioModel.render(this,"index");jw.Routing.lastPg="portfolio/index"})});return{lastPg:null,init:function(){e.run()}}}(jQuery);jw.Main=function(){return{init:function(){jw.head=$("head");jw.body=$("body");jw.main=$(".main");jw.Routing.init();$(".dateYear").text(jw.Utils.getYear())}}}();$(function(){var f=setInterval(function(){jw.scriptsLoaded===jw.numScripts&&(clearInterval(f),jw.Main.init())},20)});
