(function(a,c,b,d,g,f,e){a.GoogleAnalyticsObject=g;a[g]=a[g]||function(){(a[g].q=a[g].q||[]).push(arguments)};a[g].l=1*new Date;f=c.createElement(b);e=c.getElementsByTagName(b)[0];f.async=1;f.src=d;e.parentNode.insertBefore(f,e)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-43015655-1","jonmann20.github.io");ga("send","pageview");
var utils=function(){return{degToRad:function(a){return 0.017453292519943295*a},printMouse:function(){$("canvas").on("mousemove",function(a){console.log(a.offsetX,a.offsetY)})},printDir:function(a){switch(a){case 0:console.log("Dir.NONE");break;case 1:console.log("Dir.TOP");break;case 2:console.log("Dir.BOT");break;case 3:console.log("Dir.LEFT");break;case 4:console.log("Dir.RIGHT");break;case 5:console.log("Dir.IN");break;default:console.log("Dir.unknown")}}}}(),Dir=Object.freeze({NONE:0,TOP:1,BOT:2,
LEFT:3,RIGHT:4,IN:5}),Inv_e=Object.freeze({NOT_HIT:0,HIT_WHITE:1,HIT_RED:2}),KeyCode=Object.freeze({ENTER:13,J:74,K:75}),bullet={color:"rgba(0, 182, 255, .85)",w:19.5,h:9,speed:3.3};window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(a){setTimeout(a,16.6666666667)}}();
var audio=function(){return{bgMusic:new Audio("audio/firstChiptune/firstChiptune.mp3"),enterSound:new Audio("audio/synthetic_explosion_1.mp3"),itemPickedUp:new Audio("audio/life_pickup.mp3"),heartbeat:new Audio("audio/heartbeat.mp3"),jump:new Audio("audio/jump.mp3"),thud:new Audio("audio/thud.mp3"),step:new Audio("audio/step.mp3"),effort:new Audio("audio/woosh.mp3"),discovery:new Audio("audio/spell3.mp3"),enemyDeath:new Audio("audio/death.mp3"),heroDeath:new Audio("audio/DiscsOfTron_Cascade.mp3"),
enchant:new Audio("audio/enchant.mp3"),isOn:!1,play:function(a,c){c="undefined"!==typeof c?c:!0;if(a.ended)a.play();else if(c||0===a.currentTime)a.pause(),a.currentTime=0,a.play()},handleMuteButton:function(){$(".audioState").hasClass("off")?($(".audioState span").removeClass("icon-volume-mute").addClass("icon-volume-medium"),$(".audioState").removeClass("off"),$(".audioState").addClass("on"),audio.mute(!1)):($(".audioState span").removeClass("icon-volume-medium").addClass("icon-volume-mute"),$(".audioState").removeClass("on"),
$(".audioState").addClass("off"),audio.mute(!0))},mute:function(a){(audio.discovery.muted=audio.enterSound.muted=audio.bgMusic.muted=audio.itemPickedUp.muted=audio.heartbeat.muted=audio.effort.muted=audio.thud.muted=audio.jump.muted=audio.step.muted=audio.enemyDeath.muted=audio.heroDeath.muted=audio.enchant.muted=a)?audio.bgMusic.pause():audio.bgMusic.play();audio.isOn=!a}}}(),Graphics=function(){var a=1,c=!1,b=1;return{blinkText:function(d,g,f,e){e="undefined"!==typeof e?e:"PRESS ENTER";if(1.35<=
b||0.02>=b)c=!c;b+=c?-0.02:0.02;a=1<b?1:b;ctx.font=d+"px 'Press Start 2P'";d=ctx.measureText(e).width;ctx.fillStyle="rgba(233, 233, 233,"+a+")";ctx.fillText(e,g-d/2,f)},drawEllipse:function(a,c,b,e){var k=0.5522848*(b/2),h=0.5522848*(e/2),l=a+b,m=c+e;b=a+b/2;e=c+e/2;ctx.beginPath();ctx.moveTo(a,e);ctx.bezierCurveTo(a,e-h,b-k,c,b,c);ctx.bezierCurveTo(b+k,c,l,e-h,l,e);ctx.bezierCurveTo(l,e+h,b+k,m,b,m);ctx.bezierCurveTo(b-k,m,a,e+h,a,e);ctx.closePath();ctx.fill()},drawRotate:function(a,c,b,e){ctx.save();
ctx.translate(c,b);ctx.rotate(utils.degToRad(e));ctx.translate(0.5*-a.width,0.5*-a.height);ctx.drawImage(a,0,0);ctx.restore()}}}(),Physics=function(){return{isCollision:function(a,c,b,d){d="undefined"!==typeof d?a.x+a.lvlX:a.x;return d+b<=c.x+c.w&&c.x+b<=d+a.w&&a.y+b<=c.y+c.h&&c.y+b<=a.y+a.h?!0:!1}}}(),GameObj=function(a,c,b,d,g){var f=null,e=!1;"undefined"!==typeof g&&(f=new Image,f.onload=function(){e=!0},f.src=g);return{initX:a,x:a,initY:c,y:c,w:b,h:d,vY:0,updatePos:function(){this.y=this.y<FULLH-
game.padFloor-this.h?this.y+this.vY:FULLH-game.padFloor-this.h},draw:function(){e?ctx.drawImage(f,this.x,this.y):(ctx.fillStyle="red",ctx.fillRect(this.x,this.y,this.w,this.h))},getImg:function(){return f}}},GameItem=function(){function a(){return function(){this.visible&&!this.collected&&c.apply(this)}}var c=null;return{collected:!1,holding:!1,visible:!0,val:-1,init:function(b,d,g){$.extend(this,b);this.val=d;"undefined"!==typeof g&&(this.visible=g);c=this.draw;this.draw=a()}}},Enemy=function(){function a(){return function(){if(d||
g){if(1<b){var a=this.w/b*this.health;ctx.fillStyle="red";ctx.fillRect(this.x,this.y-12,a,4)}ctx.save();g&&(ctx.globalAlpha=0.3);c.apply(this);ctx.restore()}}}var c=null,b=0,d=!0,g=!1,f=!0;return{active:!1,health:0,init:function(d,f){$.extend(this,d);this.health=b=f;c=this.draw;this.draw=a()},update:function(){if(g){if(this.x+=f?2:-2,this.y-=14,0>this.x||this.x>FULLW)g=!1}else d&&this.active&&0===game.totalTicks%3&&(this.x<hero.x?++this.x:this.x>hero.x&&--this.x)},death:function(){f=hero.dir==Dir.RIGHT;
audio.enemyDeath.play();hero.xp+=2;d=!1;g=!0}}},startScreen=function(){function a(){lastKeyDown==KeyCode.ENTER?(++game.lvl,audio.enterSound.play(),audio.bgMusic.pause(),setTimeout(function(){audio.bgMusic=new Audio("audio/inspiredBySparkMan/sparkBoy.mp3");audio.bgMusic.loop=!0;audio.bgMusic.volume=0.45;audio.isOn?audio.bgMusic.play():audio.bgMusic.pause()},1E3),game.start()):requestAnimFrame(startScreen.loop)}var c=String.fromCharCode("169")+" 2013 JON WIEDMANN";return{loop:function(){a();ctx.fillStyle=
"#000";ctx.fillRect(0,0,FULLW,FULLH+game.padHUD);ctx.font="29px 'Press Start 2P'";var b=HALFW-ctx.measureText("JON'S").width/2+11,d=58;ctx.setTransform(1,0,-0.4,1.4,0,0);ctx.fillStyle="#222";ctx.fillText("J",b+4,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("J",b,d);ctx.setTransform(1,0,-0.2,1.4,0,0);ctx.fillStyle="#222";ctx.fillText("O",b+32,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("O",b+28,d);ctx.setTransform(1,0,0.05,1.41,0,-1);ctx.fillStyle="#222";ctx.fillText("N",b+58,d+3);ctx.fillStyle="#ff6a00";
ctx.fillText("N",b+54,d);ctx.setTransform(1,0,0.23,1.4,0,0);ctx.fillStyle="#222";ctx.fillText("'",b+78,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("'",b+74,d);ctx.setTransform(1,0,0.42,1.4,0,0);ctx.fillStyle="#222";ctx.fillText("S",b+95,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("S",b+91,d);ctx.font="36px 'Press Start 2P'";b=HALFW-ctx.measureText("QUEST").width/2+30;d=98;ctx.setTransform(1,0,-0.5,1.6,0,0);ctx.fillStyle="#222";ctx.fillText("Q",b+4,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("Q",b,d);ctx.setTransform(1,
0,-0.25,1.6,0,0);ctx.fillStyle="#222";ctx.fillText("U",b+26,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("U",b+22,d);ctx.setTransform(1,0,0.03,1.6,0,0);ctx.fillStyle="#222";ctx.fillText("E",b+50,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("E",b+46,d);ctx.setTransform(1,0,0.25,1.6,0,0);ctx.fillStyle="#222";ctx.fillText("S",b+74,d+3);ctx.fillStyle="#ff6a00";ctx.fillText("S",b+70,d);ctx.setTransform(1,0,0.5,1.6,0,0);ctx.fillStyle="#222";ctx.fillText("T",b+90,d+4);ctx.fillStyle="#ff6a00";ctx.fillText("T",
b+86,d);ctx.setTransform(1,0,0,1,0,0);Graphics.blinkText(22,HALFW,HALFH+81);ctx.font="13px 'Press Start 2P'";ctx.fillStyle="#ddd";ctx.fillText(c,HALFW-ctx.measureText(c).width/2,FULLH+44)}}}(),level=function(){function a(a,c){var b=0,d;for(d in a)"none"!==a[d]&&(e[d]=new Image,e[d].onload=function(){c(this.num)},e[d].src=a[d],e[d].num=b),++b}var c=null,b=null,d=null,g=null,f=Array(5),e={};return{collisionPts:[],width:0,init:function(){g=GameObj(238,FULLH+31,25,24,"img/medKit.png");d=GameObj(342,FULLH+
31,25,25,"img/syringe.png");c=GameObj(447,FULLH+32,24,24,"img/shuriken.png");b=GameObj(548,FULLH+33,22,24,"img/cash.png");level.collisionPts=[{obj0:{x:310,y:161,w:200,h:30},obj1:{x:600,y:95,w:200,h:30},obj2:{x:562,y:230,w:300,h:30}}];for(var e=0;5>e;++e)f[e]={status:!1,bgColor:"#"+Math.floor(16777215*Math.random()).toString(16)};a({lvl0:"img/lvl0.jpg",lvl1:"none"},function(a){f[a].status=!0});level.reset();lvl0.init()},reset:function(){level.width=3198;hero.x=23;hero.y=canvas.height-hero.h;hero.isJumping=
!1;hero.bulletArr.length=0},update:function(){switch(game.lvl){case 0:lvl0.update()}},updateObjs:function(){switch(game.lvl){case 0:lvl0.updateObjs()}},render:function(){f[game.lvl].status?ctx.drawImage(e["lvl"+game.lvl],hero.lvlX,0,FULLW,FULLH,0,0,FULLW,FULLH):(ctx.fillStyle=f[game.lvl].bgColor?f[game.lvl].bgColor:"#222",ctx.fillRect(0,0,FULLW,FULLH));ctx.fillStyle="#070707";ctx.fillRect(0,FULLH,FULLW,game.padHUD);ctx.fillStyle="#ddd";ctx.font="12px 'Press Start 2P'";ctx.fillText("HP-"+hero.healthLvl,
15,FULLH+24);ctx.fillText("MP-"+hero.manaLvl,15,FULLH+48);ctx.fillText("XP",15,FULLH+71);ctx.fillText(hero.medKits,210,FULLH+50);g.draw();ctx.fillText(hero.manaKits,315,FULLH+50);d.draw();ctx.fillText(hero.ammo,410,FULLH+50);c.draw();ctx.fillText(hero.cash,515,FULLH+50);b.draw();var a=Math.floor(game.actualTime/60),h=game.actualTime%60;10>h&&(h="0"+h);10>a&&(a="0"+a);ctx.fillText(a+":"+h,FULLW-84,FULLH+34);switch(game.lvl){case 0:lvl0.render()}},drawAfterHero:function(){0===game.lvl&&lvl0.crate.holding&&
lvl0.crate.draw()}}}(),lvl0=function(){var a=null,c=null,b=null,d=null,g=[];return{init:function(){b=GameItem();b.init(GameObj(680,71,20,24,"img/sack.png"),5);a=Enemy();a.init(GameObj(2100,FULLH-game.padFloor-38+1,28,38,"img/cyborgBnW.png"),1);c=GameItem();c.init(GameObj(140,50,22,24,"img/cash.png"),10,!1);lvl0.crate=GameItem();lvl0.crate.init(GameObj(500,FULLH-game.padFloor-26,24,26,"img/crate.png"));d=GameObj(1100,80,340,190,"img/belt.png")},update:function(){c.updatePos();a.update();!b.collected&&
Physics.isCollision(hero,b,0)&&(b.collected=!0,audio.itemPickedUp.play(),hero.ammo+=b.val);if(c.visible)!c.collected&&Physics.isCollision(hero,c,0)&&(c.collected=!0,audio.itemPickedUp.play(),hero.cash+=c.val);else for(var f=0;f<hero.bulletArr.length;++f)Physics.isCollision(hero.bulletArr[f],c,-17)&&(c.visible=!0,c.vY=4,audio.discovery.play());lvl0.crate.holding?(lvl0.crate.x=hero.dir==Dir.RIGHT?hero.x+22:hero.x-22,lvl0.crate.y=hero.y):Physics.isCollision(hero,lvl0.crate,12)&&(hero.isCarrying=!0,lvl0.crate.holding=
!0,lvl0.crate.vY=6.5);lvl0.crate.updatePos();if(0<a.health){Physics.isCollision(hero,a,0)&&(a.active=!0,hero.invincible||(audio.play(audio.heartbeat,!0),hero.invincible=!0,--hero.health));for(f=0;f<hero.bulletArr.length;++f){var e=!1;Physics.isCollision(hero.bulletArr[f],a,0)&&(e=!0,audio.play(audio.thud,!0));e&&(a.active=!0,hero.bulletArr.splice(f,1),--a.health,0>=a.health&&a.death())}Physics.isCollision(hero,d,0)&&(hero.isJumping=!1,hero.onObj=!0,f=d.initY+d.h-hero.h,e=Math.abs(hero.lvlX-680),hero.y=
-0.52845528455*e+f,hero.onObjY=hero.y)}},updateObjs:function(){b.x-=hero.vX;a.x-=hero.vX;c.x-=hero.vX;d.x-=hero.vX;lvl0.crate.x-=hero.vX},render:function(){b.collected||b.draw();c.draw();a.draw();d.draw();lvl0.crate.holding?0===hero.vX&&(lvl0.crate.x+=hero.dir==Dir.RIGHT?-20:24,lvl0.crate.y+=6):lvl0.crate.draw();for(var f=0;f<g.length;++f)g[f].draw()}}}(),game=function(){function a(b){0<b-d&&(game.renderTimeBtw=b-d);d=b;requestAnimFrame(a);level.render();hero.render();level.drawAfterHero();b=1E3/
game.renderTimeBtw;"Infinity"!=b&&f.push(b);if(0===game.totalTicks%120){b=0;for(var g in f)b+=f[g];c=Math.floor(b/f.length);f=[]}ctx.fillStyle="#ddd";ctx.font="12px 'Press Start 2P'";ctx.fillText(c+" FPS",FULLW-84,FULLH+65)}var c=0,b=0,d=0,g=0,f=[0];return{gravity:0.2,padBot:119,padHUD:80,padFloor:39,lvl:-1,updateTimeBtw:0,renderTimeBtw:0,totalTicks:0,actualTime:0,start:function(){setInterval(function(){++game.totalTicks;var a=(new Date).getTime();0<a-b&&(game.updateTimeBtw=a-b);b=a;for(g+=game.updateTimeBtw;g>=
game.updateTimeBtw;)hero.update(),level.update(),g-=game.updateTimeBtw},1E3/120);a()}}}(),hero=function(){var a=null,c=null,b=!1,d=null,g=!0,f=!1,e=[];return{x:0,y:0,sx:0,sy:0,lvlX:0,w:28,h:38,vX:0,vY:0,maxVx:3.7,maxVy:3.7,aX:0.19,aY:0.59,jumpMod:4,jumpMod0:4,dir:Dir.RIGHT,isJumping:!1,isCarrying:!1,onGround:!0,onObj:!0,onObjX:-1,onObjY:-1,invincible:!1,invincibleTimer:120,invincibleTimer0:120,health:4,maxHealth:5,medKits:1,healthLvl:1,mana:0,maxMana:4,manaKits:1,manaLvl:1,ammo:20,cash:0,lvl:1,xp:0,
xpNeeded:50,bulletArr:[],physics:null,init:function(){d=new Image;d.onload=function(){b=!0};d.src="../dungeon/web/img/sprites/player/player.png";$.get("../dungeon/web/img/sprites/player/player.xml",function(a){a=$(a).find("sprite");$(a).each(function(){var a=$(this).attr("n"),b=$(this).attr("x"),c=$(this).attr("y"),a=a.substring(0,a.length-4);e[a]={x:b,y:c}})});a=HeroInputComponent();a.init();hero.physics=HeroPhysicsComponent();c=HeroGraphicsComponent();c.init()},offObj:function(){hero.onObj=!1;hero.onObjX=
-1;hero.onObjY=-1},update:function(){a.check();hero.physics.updatePosition();hero.physics.checkCollision();hero.invincible&&--hero.invincibleTimer;0>=hero.invincibleTimer&&(hero.invincible=!1,hero.invincibleTimer=hero.invincibleTimer0);0>=hero.health&&!f&&(audio.heroDeath.play(),audio.bgMusic.muted=!0,alert("You died"),location.reload(),f=!0);0===game.totalTicks%30&&(g=!g);var b={x:0,y:0};hero.isCarrying&&0===hero.vX?b=e.playerDown:hero.dir==Dir.RIGHT?b=0<hero.vX?Math.abs(hero.vX)<=3.5*hero.aX?e.playerRight_Step:
g?e.playerRight_Run1:e.playerRight_Run2:e.playerRight:hero.dir==Dir.LEFT&&(b=0>hero.vX?Math.abs(hero.vX)<=3.5*hero.aX?e.playerLeft_Step:g?e.playerLeft_Run1:e.playerLeft_Run2:e.playerLeft);var c=hero.invincibleTimer%20;hero.invincible&&0<=c&&6>=c&&(b={x:-1,y:-1});hero.sx=b.x;hero.sy=b.y},render:function(){b&&0<=hero.sx&&0<=hero.sy&&ctx.drawImage(d,hero.sx,hero.sy,hero.w,hero.h,hero.x,hero.y,hero.w,hero.h);c.drawBullets();c.drawHealth();c.drawMana();c.drawXP()}}}(),HeroGraphicsComponent=function(){var a=
null;return{init:function(){a=new Image;a.src="img/shuriken.png";a.onload=function(){}},drawBullets:function(){for(var c=0;c<hero.bulletArr.length;++c){var b=hero.bulletArr[c].dirR?hero.w:0;hero.bulletArr[c].deg+=5;Graphics.drawRotate(a,hero.bulletArr[c].x+b,hero.bulletArr[c].y+20,hero.bulletArr[c].deg)}},drawHealth:function(){for(var a=0;a<hero.health;++a)ctx.fillStyle="red",ctx.fillRect(80+21*a,FULLH+14,19,8)},drawMana:function(){for(var a=0;a<hero.mana;++a)ctx.fillStyle="#00b6ff",ctx.fillRect(80+
21*a,FULLH+37,19,8)},drawXP:function(){ctx.fillStyle="#ddd";ctx.font="12px 'Press Start 2P'";ctx.fillText((10>hero.xp?"0":"")+hero.xp+"/"+hero.xpNeeded,80,FULLH+71)}}},HeroPhysicsComponent=function(){return{updatePosition:function(){hero.x!=hero.x+hero.vX&&audio.step.play();(hero.dir==Dir.RIGHT&&hero.x>=canvas.width/2+35||hero.dir==Dir.LEFT&&hero.x<=canvas.width/2-45)&&0<=hero.lvlX+hero.vX&&hero.lvlX+hero.vX<=level.width-canvas.width?(hero.lvlX+=hero.vX,level.updateObjs()):hero.x+=hero.vX;hero.y+=
hero.vY},checkCollision:function(){for(var a=0;a<hero.bulletArr.length;++a)hero.bulletArr[a].x+=hero.bulletArr[a].dirR?bullet.speed:-bullet.speed,(hero.bulletArr[a].x>canvas.width||0>hero.bulletArr[a].x)&&hero.bulletArr.splice(a,1);hero.onGround=!1;hero.y<-hero.h?(hero.y=-hero.h,hero.vY=0):hero.y>=canvas.height-game.padBot-hero.h?(hero.y=canvas.height-game.padBot-hero.h,hero.isJumping=!1,hero.onGround=!0,hero.vY=0):hero.onObj&&(hero.y=hero.onObjY,hero.vY=0);0>hero.x?(hero.x=0,hero.vX=0):hero.x>canvas.width-
hero.w&&(hero.x=canvas.width-hero.w,hero.vX=0);var a=game.lvl,c;for(c in level.collisionPts[a]){var b=level.collisionPts[a][c],d=hero.physics.objCollision(b);if(d!=Dir.NONE){d==Dir.LEFT?(hero.onObjX=b.x-hero.lvlX-hero.w,hero.onObjLvlX=hero.lvlX):d==Dir.RIGHT?(hero.onObjX=b.x-hero.lvlX+b.w,hero.onObjLvlX=hero.lvlX):d==Dir.TOP?(hero.onObjY=hero.y=b.y-hero.h,hero.isJumping=!1,hero.onObj=!0):d==Dir.BOT&&(-4>hero.vY&&audio.play(audio.thud,!0),hero.onObjY=hero.y=b.y+b.h,hero.jumpMod=0,hero.vY=0);if(d==
Dir.LEFT||d==Dir.RIGHT)hero.x=hero.onObjX,hero.lvlX=hero.onObjLvlX;break}}d==Dir.NONE&&hero.offObj()},objCollision:function(a){var c=Dir.NONE;Physics.isCollision(hero,a,0,!0)&&(c=Dir.IN,hero.dir==Dir.RIGHT&&hero.lvlX-hero.x<a.x?c=Dir.LEFT:hero.x+hero.lvlX+hero.w>a.x+a.w&&(c=Dir.RIGHT),hero.x!=hero.onObjX&&hero.y+hero.h-17<a.y&&0<hero.vY||hero.onObj?c=Dir.TOP:hero.y+hero.h>a.y+a.h&&(c=Dir.BOT));return c}}},HeroInputComponent=function(){return{init:function(){keysDown={};lastKeyDown=-1;addEventListener("keydown",
function(a){32==a.keyCode?a.preventDefault():77==a.keyCode?audio.handleMuteButton():66==a.keyCode?$(".resize").trigger("click"):75!=a.keyCode||hero.isJumping||75==lastKeyDown&&75 in keysDown||!hero.onObj&&!hero.onGround?74!=a.keyCode||74==lastKeyDown&&74 in keysDown||!(0<hero.ammo)||hero.isCarrying||(audio.play(audio.effort),hero.bulletArr[hero.bulletArr.length]={x:hero.x,y:hero.y,w:bullet.w,h:bullet.h,dirR:hero.dir==Dir.RIGHT,deg:0},--hero.ammo):(audio.jump.play(),hero.vY=0,hero.isJumping=!0,hero.offObj());
lastKeyDown=a.keyCode;keysDown[a.keyCode]=!0},!1);addEventListener("keyup",function(a){delete keysDown[a.keyCode]},!1)},check:function(){var a=!1;hero.isJumping?0<hero.jumpMod?hero.vY-=hero.aY*hero.jumpMod--:a=!0:(hero.jumpMod=hero.jumpMod0,a=!0);a&&(a=hero.vY+game.gravity,hero.vY=a>hero.maxVY?hero.maxVy:a);a=!1;65 in keysDown&&(hero.vX=Math.abs(hero.vX-hero.aX)>hero.maxVx?-hero.maxVx:hero.vX-hero.aX,hero.dir=Dir.LEFT,a=!0);68 in keysDown&&(hero.vX=Math.abs(hero.vX+hero.aX)>hero.maxVx?hero.maxVx:
hero.vX+hero.aX,hero.dir=Dir.RIGHT,a=!0);Math.abs(hero.vX)<hero.aX?hero.vX=0:a||(hero.vX/=1.26);32 in keysDown&&(lvl0.crate.holding=!1,hero.isCarrying=!1);72 in keysDown&&0<hero.medKits&&hero.health<hero.maxHealth&&(++hero.health,--hero.medKits,audio.play(audio.enchant,!0));82 in keysDown&&!(17 in keysDown)&&0<hero.manaKits&&hero.mana<hero.maxMana&&(++hero.mana,--hero.manaKits,audio.play(audio.enchant,!0))}}};
jq.Main=function(){function a(){audio.bgMusic.loop=!0;audio.bgMusic.volume=0.7;audio.bgMusic.pause();audio.enemyDeath.volume=0.6;audio.jump.volume=0.4;audio.thud.volume=0.78;audio.discovery.volume=0.7;audio.mute(!0);$(".audioState").on("click",audio.handleMuteButton);var a=!1;$(".resize").on("click",function(){if(a)$(canvas).css({width:"",height:""}),$(this).attr("class","resize off"),$(this).children("span").attr("class","icon-expand");else{$(canvas).css({width:"100%"});var b=$(canvas).width();$(canvas).css({height:0.611*
b});$(this).attr("class","resize on");$(this).children("span").attr("class","icon-contract")}a=!a});jq.debug||audio.handleMuteButton()}return{init:function(){canvas=$("canvas")[0];ctx=canvas.getContext("2d");FULLW=canvas.width;FULLH=canvas.height;FULLH-=game.padHUD;HALFW=FULLW/2;HALFH=FULLH/2;a();ctx.fillStyle="#e1e1e1";ctx.font="25px 'Press Start 2P'";ctx.fillText("LOADING...",HALFW-80,HALFH+20);level.init();hero.init();setInterval(function(){++game.actualTime},1E3);startScreen.loop()}}}();
$(function(){var a=setInterval(function(){jq.scriptsLoaded===jq.numScripts&&(jq.Main.init(),clearInterval(a))},10)});
